account = input('请输入账号:')
password = input('请输入密码:')
name = input('请输入姓名:')
money = 999999#原有存款
print('-'*20)
print('')
print('')
print('已登录')
print('')
print('-'*20)
print('')
need = input('请输入取款金额:')
su = money-int(need)
print(su)
